### ISSUE TITLE
Use keywind in development mode

### ISSUE THREAD

**Issue by Quadrisheriff** [lukin/keywind#29]
Hey there. Can you guide me on how to use Keywind in development mode? Any help will be appreciated.

**Comment by EternalDeiwos** [comment]
Hey @Quadrisheriff you can use this `docker-compose.yml`:

```yaml
version: '3.7'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - ./theme:/opt/keycloak/themes:ro
      - db-data:/opt/keycloak/data
    environment:
      KEYCLOAK_ADMIN: keycloak
      KEYCLOAK_ADMIN_PASSWORD: password
    command:
      - start-dev
      - --spi-theme-static-max-age=-1
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
    ports:
      - 8080:8080

volumes:
  db-data: {}

```
